### ISSUE TITLE
https Support?

### ISSUE THREAD

**Issue by discgolfdc** [fredl99/YOURLS-Upload-and-Shorten#23]
I know that this project doesn't seem to have been maintained for however long, but I wanted to put it here that it would be great to have a way to force https.  Thanks!

**Comment by fredl99** [comment]
Thanks for your input!

I'm not sure if I get it right. It's not up to the plugin to force any type of connection scheme. It's only a matter of configuration. If your YOURLS instance is running over TLS, then uploads should do as well. On the other side, if you configure the plugin to generate https short-links, that would meet your goal, too.

Beyond that, redirection of http requests to https is usually done at the server's configuration.

N.S.: Regarding maintainance...
As you can see, I'm constantly watching this space to jump in with assistance if needed. Further development might be a bit slow since the plugin works pretty well, at least for my needs. Seven years is a really long time nowadays, considering I have received exactly one donation for it so far... (Not complaining, only for the records!)

**Comment by discgolfdc** [comment]
I screwed up.  Yes, I can control it.  I just copied the "define" lines
from the instructions "as-is", not realizing I should change the http to
https on the URL definition.  Once I did that, all was well.

Cheers, and thanks for replying.

**Comment by fredl99** [comment]
Fine!

I should definately adjust the instructions to modern requirements. On the other hand that will surely trigger some requests the other way around 😀
I think I will just add according hints.

Glad I could help you and thanks for your feedback!
Closing the issue.
