### ISSUE TITLE
Upload failed, sorry! The error was 0

### ISSUE THREAD

**Issue by lexpostma** [fredl99/YOURLS-Upload-and-Shorten#7]
Hi Fredl,

I can't get your plugin to work for me. I've had it for 6 months, hasn't worked yet. Also not with the latest commits. 

I'm trying to upload a file called `CV-Lex-Postma-2016-09-nl-web.pdf`. I tried all different methods of filename alteration. 

YOURLS is running with Apache2 on a Digital Ocean VPS running `ubuntu4.19`

I'm using the following lines in config.php
```
define( 'SHARE_URL', 'http://lxpst.me/uploads/' );
define( 'SHARE_DIR', '/var/www/lxpst.me/public_html/uploads/' );
```
_(yes the target folder `uploads` exists)_

I've tried the `chmod` line in your README without succes.

Can you help me out?

**Comment by fredl99** [comment]
Hi @lexpostma 

I'm sorry to see you wasted half a year without success. Let's see...

At this point I can only guess what could be wrong there. I need a bit of input.

- Do you get an error message? (I suppose yes, the one that's mentioned?)
- is `/var/www/lxpst.me/public_html/` your standard web-directory?
- do you use YOURLS also in a standard fashion, I mean: creating short-links to foreign URLs? Does this work?
- is the file accessible by its real URL? (`http://lxpst.me/uploads/CV-Lex-Postma-2016-09-nl-web.pdf` that is?)
- have you tried another location for storing your uploads? (and adjusting the config accordingly)

The last question is the most important at the moment, because I guess there's a chicken-egg problem together with YOURLS. Scenario: You upload a file and create a short-link. When you visit that URL, YOURLS jumps in and checks where the forwarding should go. (-> To the real file in the same subfolder). So your browser calls that new URL, where YOURLS is still listening (remember it's the same folder). But now it cannot find the requested link in it's database, which should lead to a 404 error.
I have assumed a standard setup of YOURLS here and this problem could be solved somehow. Therefore it might help to know a bit more about the rest of your configuration.

However, I don't really catch the advantage of a short link which is almost as long as the original file. I'd rather use short-URLs directly under the domain name and/or dump the real files somewhere else (where Apache still can access them of course). The plugin [Yourls Swap Short Url](https://github.com/gerbz/Yourls-Swap-Short-Url) will be your friend for that.

Let me know please. I'm trying to help you.

**Comment by lexpostma** [comment]
Hi @fredl99,

Thanks for your quick reply, sorry for my late one... 

- The error I get is _"Upload failed, sorry! The error was 0"_. It's an error in YOURLS, in red text on the plugin page.

<img width="652" alt="schermafbeelding 2017-01-29 om 16 24 50" src="https://cloud.githubusercontent.com/assets/7419685/22405266/5daba6fa-e640-11e6-9806-51e89ea621a3.png">

- `/var/www/lxpst.me/public_html/` is indeed my web-directory
- The rest of YOURLS works without any issues for me
- The files I try to upload through your plugin aren't accessible, they don't seem to get uploaded at all. The `/uploads` directory is empty. The entire issue happens at the upload, so before any URL-shortening has started.
- I just tried another directory (`/files`), but it still doesn't work.

My best guess is that it's a permissions issue, but I've done the `chmod +rw /full/path/to/httpd/directory` command you have in your readme on a bunch of folders:

- `chmod +rw /var/www/lxpst.me/public_html/uploads`
- `chmod +rw /var/www/lxpst.me/public_html/files`
- `chmod +rw /var/www/lxpst.me/public_html`
- `chmod +rw /var/www/lxpst.me/`

Is there any other command I should try?

**Comment by fredl99** [comment]
Well, ok...

Could you give me the output of `ls -l /var/www/lxpst.me/public_html` please? You may obfuscate any sensible data, but the line regarding your upload directory should be visible.

Do you use any other PHP scripts (i.e. blogs, wikis or the like) that require write permissions underneath of `/var/www/lxpst.me/public_html/`? Do these work?

**Comment by lexpostma** [comment]
I found out that `www-data` not part was of the owning user group, so I added it to the group. That didn't fix it.

What _did_ fix it was: `sudo chmod 775 /path/to/uploads`

**Comment by fredl99** [comment]
Hi @lexpostma 

Thanks for reporting! I'm glad that you could solve it and may enjoy the plugin now. 

770 would be sufficient in my opinion. 775 gives read permissions to everybody which isn't necessary. In fact, the missing 'x'-bit was the problem, so Apache couldn't enter the directory.

The 'chmod'-line you were referring to came from the readme of the original project. I was never really happy with it, because there are too many ways to do it right, depending on the server itself and the possibilities/permissions of the user. At least, it was better than nothing at all, but I think I will remove it from the readme. Explaining environmental questions is just too complex to fit into a plugin's manual.

Thanks again and I hope you like it!
