### ISSUE TITLE
SHARE_URL and SHARE_DIR

### ISSUE THREAD

**Issue by odrik** [fredl99/YOURLS-Upload-and-Shorten#8]
Hello,

I really don't understand what's correspond to the vars SHARE_URL and SHARE_DIR.

```
define( 'SHARE_URL', '???' );
define( 'SHARE_DIR', '???' );
```

Yours is perfectly configured at _**mydomain.fr/yourls**_

so what's the SHARE_URL ?

The file that contains the uploaded documents is at _**/yourls/user/plugins/upload-and-shorten/files**_

so what's the SHARE_DIR ?

I tried a lot of combinaison and never it works, when I tried to upload a file I got this error : 

> **"Upload failed, sorry! The error was 0"**

Thank you !

**Comment by fredl99** [comment]
Hi there,

The `SHARE_URL` is where the yourls short-links will point to. That means where browsers will be redirected to when they request a yourls-link. In other words: The location (=URL) of your files on the internet, where they can be accessed directly.
In your example this would be `http://mydomain.fr/yourls/` or `https://mydomain.fr/yourls/` 
Notice the protocol prefix (http[s]://) and trailing slash (/).

`SHARE_DIR` is the physical path on your webserver's filesystem, where the uploaded files are stored. 
In your example this would be something like `/var/www/virtual/user/yourls/user/plugins/upload-and-shorten/files/`
It has to be the **full path** starting at the root of the filesystem. I don't know your server and setup, so I can't tell exactly. Again, notice the trailing slash since this represents a folder.

Your example above can only work if your YOURLS installation is directly at the root level of the machine. That's quite unusual, so I suppose this is why you can't upload files there.

I hope this helps. Let me know!

**Comment by fredl99** [comment]
N.B.: About the SHARE_URL:
When you say, "Yours is perfectly configured at mydomain.fr/yourls" I guess that's where you find your control panel.
Usually you don't want your visitors to fetch your uploaded files from the very same location. Even if you store them for yourself alone, you wouldn't want to merge them together with your yourls program-files.

As a second note, the SHARE_DIR should be the one where the webserver picks the contents, when the SHARE_URL is accessed. So that one should rather be outside of the yourls install-directory, which includes the plugin-directory too.

As you can see, there's also some configuration of the webserver's setup involved. But that's way beyond the scope of the plugin's documentation.

I would suggest a separate subfolder under your domain, say `http://mydomain.fr/files/` as SHARE_URL, and a corresponding SHARE_DIR like `<your-web-directory>/files/`

In a basic setup, as like you access the folder `<your-web-directory>/yourls` via the URL `http://mydomain.fr/yourls` you would have your files residing under `<your-web-directory>/files` and accessible via `http://mydomain.fr/files`

I hope it's getting clearer now.

**Comment by odrik** [comment]
Problem resolved.

The problem was that to add ../

**Comment by fredl99** [comment]
Fine.
Now go and have fun with it! :smiley:
